# filename: app.yaml
application: tushart91
version: 1 
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
- url: /(.*\.xml)
  mime_type: text/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.ico)
  static_files: static/\1
  upload: static/(.*\.ico)

- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /.*
  script: index.application